fn main() {
	cc::Build::new()
		.files([
			"linuxdoom-1.10/i_system.c",
			"linuxdoom-1.10/i_sound.c",
			"linuxdoom-1.10/i_video.c",
			"linuxdoom-1.10/i_net.c",
			"linuxdoom-1.10/f_finale.c",
			"linuxdoom-1.10/d_net.c",
			"linuxdoom-1.10/p_doors.c",
			"linuxdoom-1.10/p_enemy.c",
			"linuxdoom-1.10/p_floor.c",
			"linuxdoom-1.10/p_map.c",
			"linuxdoom-1.10/p_maputl.c",
			"linuxdoom-1.10/p_pspr.c",
			"linuxdoom-1.10/p_spec.c",
			"linuxdoom-1.10/p_switch.c",
			"linuxdoom-1.10/r_bsp.c",
			"linuxdoom-1.10/r_data.c",
			"linuxdoom-1.10/r_draw.c",
			"linuxdoom-1.10/r_main.c",
			"linuxdoom-1.10/r_plane.c",
			"linuxdoom-1.10/r_segs.c",
			"linuxdoom-1.10/r_things.c",
			"linuxdoom-1.10/st_stuff.c",
		])
		.no_default_flags(true)
		.compiler("gcc")
		.flags(["-m32", "-g", "-fpermissive", "-DNORMALUNIX", "-DLINUX"])
		.cargo_warnings(false)
		.compile("xdoom");
	println!("cargo::rerun-if-changed=linuxdoom-1.10");
	println!("cargo::rustc-link-lib=Xext");
	println!("cargo::rustc-link-lib=X11");
	println!("cargo::rustc-link-lib=nsl");
	println!("cargo::rustc-link-lib=m");
}
