// Map level types.
// The following data structures define the persistent format
// used in the lumps of the WAD files.

#![allow(non_snake_case, non_camel_case_types, clippy::missing_safety_doc)]

use std::ffi::c_char;

// Lump order in a map WAD: each map needs a couple of lumps
// to provide a complete scene geometry description.
// pub(crate) const ML_LABEL: usize = 0; // A separator, name, ExMx or MAPxx
pub(crate) const ML_THINGS: usize = 1; // Monsters, items..
pub(crate) const ML_LINEDEFS: usize = 2; // LineDefs, from editing
pub(crate) const ML_SIDEDEFS: usize = 3; // SideDefs, from editing
pub(crate) const ML_VERTEXES: usize = 4; // Vertices, edited and BSP splits generated
pub(crate) const ML_SEGS: usize = 5; // LineSegs, from LineDefs split by BSP
pub(crate) const ML_SSECTORS: usize = 6; // SubSectors, list of LineSegs
pub(crate) const ML_NODES: usize = 7; // BSP nodes
pub(crate) const ML_SECTORS: usize = 8; // Sectors, from editing
pub(crate) const ML_REJECT: usize = 9; // LUT, sector-sector visibility	
pub(crate) const ML_BLOCKMAP: usize = 10; // LUT, motion clipping, walls/grid element

// A single Vertex.
#[repr(C)]
pub(crate) struct mapvertex_t {
	pub(crate) x: i16,
	pub(crate) y: i16,
}

// A SideDef, defining the visual appearance of a wall,
// by setting textures and offsets.
#[repr(C)]
pub(crate) struct mapsidedef_t {
	pub(crate) textureoffset: i16,
	pub(crate) rowoffset: i16,
	pub(crate) toptexture: [c_char; 8],
	pub(crate) bottomtexture: [c_char; 8],
	pub(crate) midtexture: [c_char; 8],
	// Front sector, towards viewer.
	pub(crate) sector: i16,
}

// A LineDef, as used for editing, and as input
// to the BSP builder.
#[repr(C)]
pub(crate) struct maplinedef_t {
	pub(crate) v1: i16,
	pub(crate) v2: i16,
	pub(crate) flags: i16,
	pub(crate) special: i16,
	pub(crate) tag: i16,
	// sidenum[1] will be -1 if one sided
	pub(crate) sidenum: [i16; 2],
}

// LineDef attributes.

// Solid, is an obstacle.
pub(crate) const ML_BLOCKING: i16 = 1;

// Blocks monsters only.
pub(crate) const ML_BLOCKMONSTERS: i16 = 2;

// Backside will not be present at all
//  if not two sided.
pub(crate) const ML_TWOSIDED: i16 = 4;

// If a texture is pegged, the texture will have
// the end exposed to air held constant at the
// top or bottom of the texture (stairs or pulled
// down things) and will move with a height change
// of one of the neighbor sectors.
// Unpegged textures allways have the first row of
// the texture at the top pixel of the line for both
// top and bottom textures (use next to windows).

// upper texture unpegged
pub(crate) const ML_DONTPEGTOP: i16 = 8;

// lower texture unpegged
pub(crate) const ML_DONTPEGBOTTOM: i16 = 16;

// In AutoMap: don't map as two sided: IT'S A SECRET!
pub(crate) const ML_SECRET: usize = 32;

// Sound rendering: don't let sound cross two of these.
pub(crate) const ML_SOUNDBLOCK: usize = 64;

// Don't draw on the automap at all.
pub(crate) const ML_DONTDRAW: usize = 128;

// Set if already seen, thus drawn in automap.
pub(crate) const ML_MAPPED: usize = 256;

// Sector definition, from editing.
#[repr(C)]
pub(crate) struct mapsector_t {
	pub(crate) floorheight: i16,
	pub(crate) ceilingheight: i16,
	pub(crate) floorpic: [c_char; 8],
	pub(crate) ceilingpic: [c_char; 8],
	pub(crate) lightlevel: i16,
	pub(crate) special: i16,
	pub(crate) tag: i16,
}

// SubSector, as generated by BSP.
#[repr(C)]
pub(crate) struct mapsubsector_t {
	pub(crate) numsegs: i16,
	// Index of first one, segs are stored sequentially.
	pub(crate) firstseg: i16,
}

// LineSeg, generated by splitting LineDefs
// using partition lines selected by BSP builder.
#[repr(C)]
pub(crate) struct mapseg_t {
	pub(crate) v1: i16,
	pub(crate) v2: i16,
	pub(crate) angle: u16,
	pub(crate) linedef: i16,
	pub(crate) side: i16,
	pub(crate) offset: i16,
}

// BSP node structure.

// Indicate a leaf.
pub(crate) const NF_SUBSECTOR: usize = 0x8000;

#[repr(C)]
pub(crate) struct mapnode_t {
	// Partition line from (x,y) to x+dx,y+dy)
	pub(crate) x: i16,
	pub(crate) y: i16,
	pub(crate) dx: i16,
	pub(crate) dy: i16,

	// Bounding box for each child,
	// clip against view frustum.
	pub(crate) bbox: [[i16; 4]; 2],

	// If NF_SUBSECTOR its a subsector,
	// else it's a node of another subtree.
	pub(crate) children: [u16; 2],
}

// Thing definition, position, orientation and type,
// plus skill/visibility flags and attributes.
#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct mapthing_t {
	pub(crate) x: i16,
	pub(crate) y: i16,
	pub(crate) angle: i16,
	pub(crate) ty: i16,
	pub(crate) options: i16,
}
