#![allow(non_snake_case, non_camel_case_types, clippy::missing_safety_doc)]

use std::{
	ffi::{c_char, c_void},
	ptr::{null, null_mut},
};

use crate::sounds::sfxenum_t::sfx_pistol;

// SoundFX struct.
#[repr(C)]
pub struct sfxinfo_t {
	// up to 6-character name
	pub name: *const c_char,

	// Sfx singularity (only one at a time)
	pub singularity: i32,

	// Sfx priority
	pub priority: i32,

	// referenced sound if a link
	pub link: *mut sfxinfo_t,

	// pitch if a link
	pub pitch: i32,

	// volume if a link
	pub volume: isize,

	// sound data
	pub data: *mut c_void,

	// this is checked every second to see if sound
	// can be thrown out (if 0, then decrement, if -1,
	// then throw out, if > 0, then it is in use)
	pub usefulness: i32,

	// lump number of sfx
	pub lumpnum: i32,
}
unsafe impl Sync for sfxinfo_t {}

// MusicInfo struct.
#[repr(C)]
pub struct musicinfo_t {
	// up to 6-character name
	pub name: *const c_char,

	// lump number of music
	pub lumpnum: usize,

	// music data
	pub data: *mut c_void,

	// music handle once registered
	pub handle: i32,
}

unsafe impl Sync for musicinfo_t {}

// Identifiers for all music in game.

#[repr(i32)]
#[derive(Clone, Copy)]
#[rustfmt::skip]
pub enum musicenum_t {
	mus_None,
	mus_e1m1, mus_e1m2, mus_e1m3, mus_e1m4, mus_e1m5, mus_e1m6, mus_e1m7, mus_e1m8, mus_e1m9,
	mus_e2m1, mus_e2m2, mus_e2m3, mus_e2m4, mus_e2m5, mus_e2m6, mus_e2m7, mus_e2m8, mus_e2m9,
	mus_e3m1, mus_e3m2, mus_e3m3, mus_e3m4, mus_e3m5, mus_e3m6, mus_e3m7, mus_e3m8, mus_e3m9,
	mus_inter, mus_intro, mus_bunny, mus_victor, mus_introa, mus_runnin, mus_stalks, mus_countd,
	mus_betwee, mus_doom, mus_the_da, mus_shawn, mus_ddtblu, mus_in_cit, mus_dead, mus_stlks2,
	mus_theda2, mus_doom2, mus_ddtbl2, mus_runni2, mus_dead2, mus_stlks3, mus_romero, mus_shawn2,
	mus_messag, mus_count2, mus_ddtbl3, mus_ampie, mus_theda3, mus_adrian, mus_messg2, mus_romer2,
	mus_tense, mus_shawn3, mus_openin, mus_evil, mus_ultima, mus_read_m, mus_dm2ttl, mus_dm2int,
	NUMMUSIC,
}

impl From<usize> for musicenum_t {
	fn from(value: usize) -> Self {
		if value > Self::NUMMUSIC as usize {
			panic!("Invalid musicenum_t")
		}
		unsafe { std::mem::transmute(value) }
	}
}

// Identifiers for all sfx in game.
#[repr(i32)]
#[derive(Clone, Copy, PartialEq, Eq)]
#[rustfmt::skip]
pub enum sfxenum_t {
	sfx_None,
	sfx_pistol, sfx_shotgn, sfx_sgcock, sfx_dshtgn, sfx_dbopn, sfx_dbcls, 
	sfx_dbload, sfx_plasma, sfx_bfg, sfx_sawup, sfx_sawidl, sfx_sawful, sfx_sawhit, 
	sfx_rlaunc, sfx_rxplod, sfx_firsht, sfx_firxpl, sfx_pstart, sfx_pstop, 
	sfx_doropn, sfx_dorcls, sfx_stnmov, sfx_swtchn, sfx_swtchx, sfx_plpain, 
	sfx_dmpain, sfx_popain, sfx_vipain, sfx_mnpain, sfx_pepain, sfx_slop, 
	sfx_itemup, sfx_wpnup, sfx_oof, sfx_telept, sfx_posit1, sfx_posit2, sfx_posit3, 
	sfx_bgsit1, sfx_bgsit2, sfx_sgtsit, sfx_cacsit, sfx_brssit, sfx_cybsit, 
	sfx_spisit, sfx_bspsit, sfx_kntsit, sfx_vilsit, sfx_mansit, sfx_pesit, 
	sfx_sklatk, sfx_sgtatk, sfx_skepch, sfx_vilatk, sfx_claw, sfx_skeswg, 
	sfx_pldeth, sfx_pdiehi, sfx_podth1, sfx_podth2, sfx_podth3, sfx_bgdth1, 
	sfx_bgdth2, sfx_sgtdth, sfx_cacdth, sfx_skldth, sfx_brsdth, sfx_cybdth, 
	sfx_spidth, sfx_bspdth, sfx_vildth, sfx_kntdth, sfx_pedth, sfx_skedth, 
	sfx_posact, sfx_bgact, sfx_dmact, sfx_bspact, sfx_bspwlk, sfx_vilact, 
	sfx_noway, sfx_barexp, sfx_punch, sfx_hoof, sfx_metal, sfx_chgun, sfx_tink, 
	sfx_bdopn, sfx_bdcls, sfx_itmbk, sfx_flame, sfx_flamst, sfx_getpow, sfx_bospit, 
	sfx_boscub, sfx_bossit, sfx_bospn, sfx_bosdth, sfx_manatk, sfx_mandth, 
	sfx_sssit, sfx_ssdth, sfx_keenpn, sfx_keendt, sfx_skeact, sfx_skesit, 
	sfx_skeatk, sfx_radio,
	NUMSFX,
}

impl From<usize> for sfxenum_t {
	fn from(value: usize) -> Self {
		if value > Self::NUMSFX as usize {
			panic!("Invalid musicenum_t")
		}
		unsafe { std::mem::transmute(value) }
	}
}

// Information about all the music
#[unsafe(no_mangle)]
pub static mut S_music: [musicinfo_t; 68] = [
	musicinfo_t { name: null_mut(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e1m1".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e1m2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e1m3".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e1m4".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e1m5".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e1m6".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e1m7".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e1m8".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e1m9".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e2m1".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e2m2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e2m3".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e2m4".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e2m5".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e2m6".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e2m7".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e2m8".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e2m9".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e3m1".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e3m2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e3m3".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e3m4".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e3m5".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e3m6".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e3m7".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e3m8".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"e3m9".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"inter".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"intro".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"bunny".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"victor".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"introa".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"runnin".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"stalks".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"countd".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"betwee".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"doom".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"the_da".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"shawn".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"ddtblu".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"in_cit".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"dead".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"stlks2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"theda2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"doom2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"ddtbl2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"runni2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"dead2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"stlks3".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"romero".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"shawn2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"messag".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"count2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"ddtbl3".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"ampie".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"theda3".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"adrian".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"messg2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"romer2".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"tense".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"shawn3".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"openin".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"evil".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"ultima".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"read_m".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"dm2ttl".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
	musicinfo_t { name: c"dm2int".as_ptr(), lumpnum: 0, data: null_mut(), handle: 0 },
];

// Information about all the sfx
#[unsafe(no_mangle)]
pub static mut S_sfx: [sfxinfo_t; 109] = [
	sfxinfo_t {
		name: null(),
		singularity: 0,
		priority: 0,
		link: null_mut(),
		pitch: 0,
		volume: 0,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"pistol".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"shotgn".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"sgcock".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"dshtgn".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"dbopn".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"dbcls".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"dbload".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"plasma".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bfg".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"sawup".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"sawidl".as_ptr(),
		singularity: 0,
		priority: 118,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"sawful".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"sawhit".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"rlaunc".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"rxplod".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"firsht".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"firxpl".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"pstart".as_ptr(),
		singularity: 0,
		priority: 100,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"pstop".as_ptr(),
		singularity: 0,
		priority: 100,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"doropn".as_ptr(),
		singularity: 0,
		priority: 100,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"dorcls".as_ptr(),
		singularity: 0,
		priority: 100,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"stnmov".as_ptr(),
		singularity: 0,
		priority: 119,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"swtchn".as_ptr(),
		singularity: 0,
		priority: 78,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"swtchx".as_ptr(),
		singularity: 0,
		priority: 78,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"plpain".as_ptr(),
		singularity: 0,
		priority: 96,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"dmpain".as_ptr(),
		singularity: 0,
		priority: 96,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"popain".as_ptr(),
		singularity: 0,
		priority: 96,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"vipain".as_ptr(),
		singularity: 0,
		priority: 96,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"mnpain".as_ptr(),
		singularity: 0,
		priority: 96,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"pepain".as_ptr(),
		singularity: 0,
		priority: 96,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"slop".as_ptr(),
		singularity: 0,
		priority: 78,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"itemup".as_ptr(),
		singularity: 1,
		priority: 78,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"wpnup".as_ptr(),
		singularity: 1,
		priority: 78,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"oof".as_ptr(),
		singularity: 0,
		priority: 96,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"telept".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"posit1".as_ptr(),
		singularity: 1,
		priority: 98,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"posit2".as_ptr(),
		singularity: 1,
		priority: 98,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"posit3".as_ptr(),
		singularity: 1,
		priority: 98,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bgsit1".as_ptr(),
		singularity: 1,
		priority: 98,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bgsit2".as_ptr(),
		singularity: 1,
		priority: 98,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"sgtsit".as_ptr(),
		singularity: 1,
		priority: 98,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"cacsit".as_ptr(),
		singularity: 1,
		priority: 98,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"brssit".as_ptr(),
		singularity: 1,
		priority: 94,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"cybsit".as_ptr(),
		singularity: 1,
		priority: 92,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"spisit".as_ptr(),
		singularity: 1,
		priority: 90,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bspsit".as_ptr(),
		singularity: 1,
		priority: 90,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"kntsit".as_ptr(),
		singularity: 1,
		priority: 90,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"vilsit".as_ptr(),
		singularity: 1,
		priority: 90,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"mansit".as_ptr(),
		singularity: 1,
		priority: 90,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"pesit".as_ptr(),
		singularity: 1,
		priority: 90,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"sklatk".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"sgtatk".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"skepch".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"vilatk".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"claw".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"skeswg".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"pldeth".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"pdiehi".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"podth1".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"podth2".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"podth3".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bgdth1".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bgdth2".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"sgtdth".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"cacdth".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"skldth".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"brsdth".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"cybdth".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"spidth".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bspdth".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"vildth".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"kntdth".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"pedth".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"skedth".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"posact".as_ptr(),
		singularity: 1,
		priority: 120,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bgact".as_ptr(),
		singularity: 1,
		priority: 120,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"dmact".as_ptr(),
		singularity: 1,
		priority: 120,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bspact".as_ptr(),
		singularity: 1,
		priority: 100,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bspwlk".as_ptr(),
		singularity: 1,
		priority: 100,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"vilact".as_ptr(),
		singularity: 1,
		priority: 100,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"noway".as_ptr(),
		singularity: 0,
		priority: 78,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"barexp".as_ptr(),
		singularity: 0,
		priority: 60,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"punch".as_ptr(),
		singularity: 0,
		priority: 64,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"hoof".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"metal".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"chgun".as_ptr(),
		singularity: 0,
		priority: 64,
		link: unsafe { &raw mut S_sfx[sfx_pistol as usize] },
		pitch: 150,
		volume: 0,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"tink".as_ptr(),
		singularity: 0,
		priority: 60,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bdopn".as_ptr(),
		singularity: 0,
		priority: 100,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bdcls".as_ptr(),
		singularity: 0,
		priority: 100,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"itmbk".as_ptr(),
		singularity: 0,
		priority: 100,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"flame".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"flamst".as_ptr(),
		singularity: 0,
		priority: 32,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"getpow".as_ptr(),
		singularity: 0,
		priority: 60,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bospit".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"boscub".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bossit".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bospn".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"bosdth".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"manatk".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"mandth".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"sssit".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"ssdth".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"keenpn".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"keendt".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"skeact".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"skesit".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"skeatk".as_ptr(),
		singularity: 0,
		priority: 70,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
	sfxinfo_t {
		name: c"radio".as_ptr(),
		singularity: 0,
		priority: 60,
		link: null_mut(),
		pitch: -1,
		volume: -1,
		data: null_mut(),
		usefulness: 0,
		lumpnum: 0,
	},
];
